### PR TITLE
Docker-compose and docker-sync templates upgraded to framework 7.0.0-beta1

### PR DESCRIPTION
**Pull request by Miroslav-Stopka**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Old templates are not prepared for usage with framework 7.0.0-beta1
|New feature| No
|BC breaks| No
|Fixes issues| ...
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by boris-brtan** [comment]
Hi, any progress for this PR @vitek-rostislav ?

**Comment by vitek-rostislav** [comment]
Hi, no, TBH, I completely missed this PR. I believe we should solve this during the next upgrade of demoshop.

**Comment by boris-brtan** [comment]
hmm now i would add here also need for docker-sync-win and other stuff

**Comment by PetrHeinz** [comment]
I'm closing this PR as it is pretty old (upgrade to beta1). The only remaining problem I see s the `docker-sync.yml` so I've created a separate PR for that in #35

**Pull request closed without merging**
